---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: etherpad-app-latest
  namespace: etherpad
spec:
  type: GitHub
  pathname: https://github.com/esalierno/rhacm-labs.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: etherpad-app
  namespace: etherpad
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - etherpad-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: etherpad-app-coll
  namespace: etherpad
  labels:
    app: etherpad-app
  annotations:
    apps.open-cluster-management.io/github-path: resources/etherpad/coll
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: etherpad/etherpad-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: coll-clusters

---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: etherpad-app-prod
  namespace: etherpad
  labels:
    app: etherpad-app
  annotations:
    apps.open-cluster-management.io/github-path: resources/etherpad/prod
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: etherpad/etherpad-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: prod-clusters

