apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: coll-clusters
  namespace: etherpad
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      tenant: mds
      environment: coll
